name: e-learning
services:
  database:
    container_name: postgres
    image: postgres:14.23-alpine3.23
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - school_pg_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
  
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: database
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: 1234
      KEYCLOAK_ADMIN : admin
      KEYCLOAK_ADMIN_PASSWORD : admin
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes
    ports: 
      - "8080:8080"
    depends_on:
      - database
    command: start-dev
    
volumes:
  school_pg_data: